INCLUDEPATH += $$PWD/
greaterThan(QT_MAJOR_VERSION, 4): include($$PWD/3rdParty/FramelessHelper/FramelessHelper_lib.pri)
#include($$PWD/3rdParty/framelesshelper-2.2.1/qmake/widgets.pri)
include($$PWD/3rdParty/CuteLogger/CuteLogger.pri)
include($$PWD/3rdParty/lua/lua.pri)
include($$PWD/3rdParty/libmodbus/libmodbus.pri)
include($$PWD/3rdParty/QXlsx/QXlsx.pri)
#include($$PWD/3rdParty/qcustomplot/3rd_qcustomplot.pri)
include($$PWD/3rdParty/qtftp/qtftp.pri)
greaterThan(QT_MAJOR_VERSION, 4): include($$PWD/3rdParty/qBreakpad/qBreakpad.pri)
include($$PWD/3rdParty/iconHelper/iconHelper.pri)
include($$PWD/3rdParty/qtnotify/qtnotify.pri)
