#ifndef VERSION_H
#define VERSION_H
#define STRING_VALUE(...)   STRING_VALUE__(__VA_ARGS__)
#define STRING_VALUE__(...) #__VA_ARGS__

#define EX_VERSION_MAJOR 1
#define EX_VERSION_MINOR 0
#define EX_VERSION_PATCH 5
#define EX_VERSION_BUILD 1

#define VER_PRODUCTVERSION EX_VERSION_MAJOR, EX_VERSION_MINOR, EX_VERSION_PATCH, EX_VERSION_BUILD
#define VER_NUM            EX_VERSION_MAJOR.EX_VERSION_MINOR.EX_VERSION_PATCH.EX_VERSION_BUILD

#define VER_PRODUCTVERSION_STR STRING_VALUE(VER_NUM)  //"1.1.3.3"  //产品版本

#define VER_FILEVERSION     VER_PRODUCTVERSION  //文件版本
#define VER_FILEVERSION_STR VER_PRODUCTVERSION_STR

#define VER_COMPANYNAME_STR      "Cubenergy"
#define VER_FILEDESCRIPTION_STR  "bms_tool"  //文件说明
#define VER_INTERNALNAME_STR     "bms_tool"
#define VER_LEGALCOPYRIGHT_STR   "Copyright 2019-2022 Cubenergy"  //版权
#define VER_LEGALTRADEMARKS1_STR "All rights reserved"
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "bms_tool.exe"  //原始文件名
#define VER_PRODUCTNAME_STR      "bms_tool"      //产品名称

#define VER_COMPANYDOMAIN_STR "www.cubenergy.com.cn"

#endif  // VERSION_H
